config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :nominees
  resources :nominations do
    collection do
      get '/load_rating_form/:award_id/(:nomination_id)' => 'nominations#load_rating_form'
    end
    member do
      post 'push_back'
      post 'forward'
      post 'l1_approval'
      post 'l2_approval'
      get 'justification'
      post 'reject_single_nominee'
      post 'chairman_approval'
    end
  end
  
  get '/nominations/:id/pushback' => 'nominations#pushback'
  get '/team_nominations/new' => 'nominations#team_nomination'
  get '/individual_nominations/:type' => 'nominations#individual_nominations'
  post '/awards/:id/add_comment_to_award' => 'award#add_comment_to_award'

  resources :award_masters
  resources :cycles
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  get '/l1_dashboard' => 'homes#l1_dashboard'
  get '/admin_dashboard' => 'homes#admin_dashboard'
  get '/l2_dashboard' => 'homes#l2_dashboard'
  get '/chairman_dashboard' => 'homes#chairman_dashboard'
  get '/user_dashboard' => 'homes#user_dashboard'
end

app/models/nominee.rb
class Nominee < ApplicationRecord
  belongs_to :nomination
  belongs_to :user
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :set_nominee, only: [:show, :edit, :update, :destroy]

  # GET /nominees
  # GET /nominees.json
  def index
    @nominees = Nominee.all
  end

  # GET /nominees/1
  # GET /nominees/1.json
  def show
  end

  # GET /nominees/new
  def new
    @nominee = Nominee.new
  end

  # GET /nominees/1/edit
  def edit
  end

  # POST /nominees
  # POST /nominees.json
  def create
    @nominee = Nominee.new(nominee_params)

    respond_to do |format|
      if @nominee.save
        format.html { redirect_to @nominee, notice: 'Nominee was successfully created.' }
        format.json { render :show, status: :created, location: @nominee }
      else
        format.html { render :new }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominees/1
  # PATCH/PUT /nominees/1.json
  def update
    respond_to do |format|
      if @nominee.update(nominee_params)
        format.html { redirect_to @nominee, notice: 'Nominee was successfully updated.' }
        format.json { render :show, status: :ok, location: @nominee }
      else
        format.html { render :edit }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominees/1
  # DELETE /nominees/1.json
  def destroy
    @nominee.destroy
    respond_to do |format|
      format.html { redirect_to nominees_url, notice: 'Nominee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nominee
      @nominee = Nominee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nominee_params
      params.require(:nominee).permit(:nomination_id, :user_id, :emp_code)
    end
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/nominees/_form.html.erb
<%= form_with(model: nominee, local: true) do |form| %>
  <% if nominee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nominee.errors.count, "error") %> prohibited this nominee from being saved:</h2>

      <ul>
        <% nominee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nomination_id %>
    <%= form.text_field :nomination_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :emp_code %>
    <%= form.text_field :emp_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nominees/edit.html.erb
<h1>Editing Nominee</h1>

<%= render 'form', nominee: @nominee %>

<%= link_to 'Show', @nominee %> |
<%= link_to 'Back', nominees_path %>

app/views/nominees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nominees</h1>

<table>
  <thead>
    <tr>
      <th>Nomination</th>
      <th>User</th>
      <th>Emp code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nominees.each do |nominee| %>
      <tr>
        <td><%= nominee.nomination_id %></td>
        <td><%= nominee.user_id %></td>
        <td><%= nominee.emp_code %></td>
        <td><%= link_to 'Show', nominee %></td>
        <td><%= link_to 'Edit', edit_nominee_path(nominee) %></td>
        <td><%= link_to 'Destroy', nominee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nominee', new_nominee_path %>

app/views/nominees/new.html.erb
<h1>New Nominee</h1>

<%= render 'form', nominee: @nominee %>

<%= link_to 'Back', nominees_path %>

app/views/nominees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomination:</strong>
  <%= @nominee.nomination_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @nominee.user_id %>
</p>

<p>
  <strong>Emp code:</strong>
  <%= @nominee.emp_code %>
</p>

<%= link_to 'Edit', edit_nominee_path(@nominee) %> |
<%= link_to 'Back', nominees_path %>