config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :nominees
  resources :nominations do
    collection do
      get '/load_rating_form/:award_id/(:nomination_id)' => 'nominations#load_rating_form'
    end
    member do
      post 'push_back'
      post 'forward'
      post 'l1_approval'
      post 'l2_approval'
      get 'justification'
      post 'reject_single_nominee'
      post 'chairman_approval'
    end
  end
  
  get '/nominations/:id/pushback' => 'nominations#pushback'
  get '/team_nominations/new' => 'nominations#team_nomination'
  get '/individual_nominations/:type' => 'nominations#individual_nominations'
  post '/awards/:id/add_comment_to_award' => 'award#add_comment_to_award'

  resources :award_masters
  resources :cycles
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  get '/l1_dashboard' => 'homes#l1_dashboard'
  get '/admin_dashboard' => 'homes#admin_dashboard'
  get '/l2_dashboard' => 'homes#l2_dashboard'
  get '/chairman_dashboard' => 'homes#chairman_dashboard'
  get '/user_dashboard' => 'homes#user_dashboard'
end

app/models/award_master.rb
class AwardMaster < ApplicationRecord
  has_many :awards, dependent: :destroy
  has_many :rating_scales, dependent: :destroy
  has_many :assessment_masters, dependent: :destroy
end

app/controllers/award_masters_controller.rb
class AwardMastersController < ApplicationController
  before_action :set_award_master, only: [:show, :edit, :update, :destroy]

  # GET /award_masters
  # GET /award_masters.json
  def index
    @award_masters = AwardMaster.all
  end

  # GET /award_masters/1
  # GET /award_masters/1.json
  def show
  end

  # GET /award_masters/new
  def new
    @award_master = AwardMaster.new
  end

  # GET /award_masters/1/edit
  def edit
  end

  # POST /award_masters
  # POST /award_masters.json
  def create
    @award_master = AwardMaster.new(award_master_params)

    respond_to do |format|
      if @award_master.save
        format.html { redirect_to @award_master, notice: 'Award master was successfully created.' }
        format.json { render :show, status: :created, location: @award_master }
      else
        format.html { render :new }
        format.json { render json: @award_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /award_masters/1
  # PATCH/PUT /award_masters/1.json
  def update
    respond_to do |format|
      if @award_master.update(award_master_params)
        format.html { redirect_to @award_master, notice: 'Award master was successfully updated.' }
        format.json { render :show, status: :ok, location: @award_master }
      else
        format.html { render :edit }
        format.json { render json: @award_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /award_masters/1
  # DELETE /award_masters/1.json
  def destroy
    @award_master.destroy
    respond_to do |format|
      format.html { redirect_to award_masters_url, notice: 'Award master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award_master
      @award_master = AwardMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_master_params
      params.require(:award_master).permit(:title, :award_type)
    end
end

app/helpers/award_masters_helper.rb
module AwardMastersHelper
end

app/views/award_masters/_form.html.erb
<%= form_with(model: award_master, local: true) do |form| %>
  <% if award_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award_master.errors.count, "error") %> prohibited this award_master from being saved:</h2>

      <ul>
        <% award_master.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :award_type %>
    <%= form.text_field :award_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/award_masters/edit.html.erb
<h1>Editing Award Master</h1>

<%= render 'form', award_master: @award_master %>

<%= link_to 'Show', @award_master %> |
<%= link_to 'Back', award_masters_path %>

app/views/award_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Award Masters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Award type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @award_masters.each do |award_master| %>
      <tr>
        <td><%= award_master.title %></td>
        <td><%= award_master.award_type %></td>
        <td><%= link_to 'Show', award_master %></td>
        <td><%= link_to 'Edit', edit_award_master_path(award_master) %></td>
        <td><%= link_to 'Destroy', award_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Award Master', new_award_master_path %>

app/views/award_masters/new.html.erb
<h1>New Award Master</h1>

<%= render 'form', award_master: @award_master %>

<%= link_to 'Back', award_masters_path %>

app/views/award_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @award_master.title %>
</p>

<p>
  <strong>Award type:</strong>
  <%= @award_master.award_type %>
</p>

<%= link_to 'Edit', edit_award_master_path(@award_master) %> |
<%= link_to 'Back', award_masters_path %>