config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :nominees
  resources :nominations do
    collection do
      get '/load_rating_form/:award_id/(:nomination_id)' => 'nominations#load_rating_form'
    end
    member do
      post 'push_back'
      post 'forward'
      post 'l1_approval'
      post 'l2_approval'
      get 'justification'
      post 'reject_single_nominee'
      post 'chairman_approval'
    end
  end
  
  get '/nominations/:id/pushback' => 'nominations#pushback'
  get '/team_nominations/new' => 'nominations#team_nomination'
  get '/individual_nominations/:type' => 'nominations#individual_nominations'
  post '/awards/:id/add_comment_to_award' => 'award#add_comment_to_award'

  resources :award_masters
  resources :cycles
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  get '/l1_dashboard' => 'homes#l1_dashboard'
  get '/admin_dashboard' => 'homes#admin_dashboard'
  get '/l2_dashboard' => 'homes#l2_dashboard'
  get '/chairman_dashboard' => 'homes#chairman_dashboard'
  get '/user_dashboard' => 'homes#user_dashboard'
end

app/models/nomination.rb
class Nomination < ApplicationRecord
  include RailsStateMachine::Model

  has_many :nominees, dependent: :destroy
  has_many :ratings, dependent: :destroy
  belongs_to :nominator, polymorphic: true, optional: true
  accepts_nested_attributes_for :nominees
  accepts_nested_attributes_for :ratings
  belongs_to :award
  has_many :nomination_attachments, dependent: :destroy
  has_many :assessments, dependent: :destroy

  accepts_nested_attributes_for :nomination_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :assessments, reject_if: :all_blank, allow_destroy: true

  after_create :notify_nominator

  # validates :justification, presence: true,  length: { minimum: 50 }

  state_machine do
    state :draft, initial: true
    state :review_pending
    state :pushed_back
    state :l1_review_pending
    state :l2_review_pending
    state :final_review_pending
    state :l1_approved
    state :l1_rejected
    state :l2_approved
    state :l2_rejected
    state :approved
    state :rejected

    event :request_review do
      transitions from: [:draft, :pushed_back], to: :review_pending
    end

    event :approve do
      transitions from: :final_review_pending, to: :approved
      after_save do
        NotificationMailer.approval_notification(self).deliver_later
      end
    end

    event :reject do
      transitions from: :final_review_pending, to: :rejected
      after_save do
        NotificationMailer.rejection_notification(self).deliver_later
      end
    end

    event :push_back do
      transitions from: [:draft, :review_pending, :l1_review_pending, :l2_review_pending, :final_review_pending], to: :pushed_back
      after_save do
        NotificationMailer.pushedback_notification(self).deliver_later
      end
    end

    event :forward do
      transitions from: [:draft, :review_pending, :pushed_back], to: :l1_review_pending
      after_save do
        NotificationMailer.forward_notification(self).deliver_later
      end
    end

    event :l1_approve do
      transitions from: :l1_review_pending, to: :l2_review_pending
    end

    event :l1_reject do
      transitions from: :l1_review_pending, to: :rejected
    end

    event :l2_approve do
      transitions from: :l2_review_pending, to: :final_review_pending
    end

    event :l2_reject do
      transitions from: :l2_review_pending, to: :rejected
    end
  end

  def notify_nominator
    NotificationMailer.welcome_email(self).deliver_later
  end

  def nomination_state
    case self.state
    when "draft"
      "HR Review Pending"
    when "review_pending"
      "HR Review Pending"
    else
      self.state.titleize
    end
  end
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:push_back, :forward, :l1_approval, :l2_approval, :chairman_approval, :reject_single_nominee]
  before_action :set_nomination, only: [:show, :edit, :update, :destroy, :push_back, :forward, :l1_approval, :l2_approval, :justification, :chairman_approval, :reject_single_nominee]

  # GET /nominations
  # GET /nominations.json
  def index
    @nominations = Nomination.all
  end

  # GET /nominations/1
  # GET /nominations/1.json
  def show
  end

  def justification
    #@nomination = Nomination.find(params[:id]
    render json: {
      justification: @nomination.justification,
      attachment: (@nomination.nomination_attachments.last.attachment.identifier rescue ""),
      url: (@nomination.nomination_attachments.last.attachment.url rescue "#"),
      assessments: @nomination.assessments.as_json(:include => { :assessment_attachments => { only: :attachment } }),
    }
  end

  # GET /nominations/new
  def new
    @cycle = Cycle.current_cycle
    @awards = @cycle.awards - [@cycle.awards.find_by(title: "The Best Cross-Functional Team")]
    @users = current_user.peers.map { |u| ["#{u.emp_code.rjust(5, "0")} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
    @nomination = Nomination.new
    # @nomination.company_id = current_user.company.id rescue nil
    @nomination.nominees.build
    @nomination.nomination_attachments.build
    # if params[:award_id].nil?
    #   @award = @cycle.awards.last
    # else
    #   @award = Award.find(params[:award_id])
    # end
    # @award.award_master.rating_scales.each do |rs|
    #   @nomination.ratings.build(title: rs.title)
    # end
    # render json: @nomination.ratings
    # return
  end

  def individual_nominations
    @cycle = Cycle.current_cycle
    @type = params[:type]
    if (@type == "tmil")
      @award = @cycle.awards.find_by(title: "The Most Inspiring Leader")
      @users = current_user.peers.select { |u| @award.cadre_coverage.include?(u.employee.cadre) }.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
      @color = "green"
    elsif (@type == "tbe")
      @award = @cycle.awards.find_by(title: "The Best Employee")
      @users = current_user.peers.select { |u| @award.cadre_coverage.include?(u.employee.cadre) }.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
      @color = "blue"
    elsif (@type == "tmie")
      @award = @cycle.awards.find_by(title: "The Most Innovative Employee")
      @users = current_user.peers.select { |u| @award.cadre_coverage.include?(u.employee.cadre) }.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
      @color = "orange"
    elsif (@type == "tbpm")
      @award = @cycle.awards.find_by(title: "The Best Project Manager")
      @users = current_user.peers.select { |u| u.employee.designation == "Project Manager" }.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
      @color = "black"
    end
    @awards = [@award]

    @nomination = Nomination.new
    @nomination.nominees.build
    @nomination.nomination_attachments.build

    @award.award_master.assessment_masters.each do |am|
      a = @nomination.assessments.build(assessment_param: am.assessment_param, statement: am.statement)
      a.assessment_attachments.build
    end
    # render json: @award.award_master.assessment_masters
    # return
  end

  def team_nomination
    @cycle = Cycle.current_cycle
    @nomination = Nomination.new
    # @nomination.company_id = current_user.company.id rescue nil
    @color = "purple"
    @nomination.nominees.build
    @award = @cycle.awards.find_by(title: "The Best Cross-Functional Team")
    @users = current_user.peers.select { |u| @award.cadre_coverage.include?(u.employee.cadre) }.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
    @awards = [@award]
    @nomination.award = @award
    @award.award_master.rating_scales.each do |rs|
      @nomination.ratings.build(title: rs.title)
    end
    @award.award_master.assessment_masters.each do |am|
      a = @nomination.assessments.build(assessment_param: am.assessment_param, statement: am.statement)
      a.assessment_attachments.build
    end
    @nomination.nomination_attachments.build
  end

  def load_rating_form
    @award = Award.find(params[:award_id])
    if !params[:nomination_id].nil?
      @nomination = Nomination.find(params[:nomination_id])
      @rating_scales = @nomination.ratings
    else
      @rating_scales = @award.award_master.rating_scales
    end
    render partial: "rating_form"
  end

  # GET /nominations/1/edit
  def edit
    @cycle = Cycle.current_cycle
    @awards = @cycle.awards
    @award = @nomination.award
    case @award.title
    when "The Most Inspiring Leader"
      @color = "green"
    when "The Best Employee"
      @color = "blue"
    when "The Most Innovative Employee"
      @color = "orange"
    when "The Best Project Manager"
      @color = "black"
    when "The Best Cross-Functional Team"
      @color = "purple"
    end
    @users = current_user.peers.map { |u| ["#{u.emp_code.rjust(5, "0") rescue u.emp_code} | #{u.employee.name rescue ""} | #{u.employee.location rescue ""} | #{u.employee.sbu rescue ""}", u.id] }
    # @selected_nominees = @nomination.nominees
  end

  # POST /nominations
  # POST /nominations.json
  def create
    # render json: params
    # return
    @nomination = Nomination.new(nomination_params)
    if params[:nomination][:nominees_attributes]["0"]["user_id"].class.to_s == "Array"
      @nomination.nominees.destroy_all
      params[:nomination][:nominees_attributes]["0"]["user_id"].each do |u|
        @nomination.nominees.new(user_id: u)
      end
    end
    respond_to do |format|
      @nomination.company_id = current_user.company.id rescue nil
      if @nomination.save
        format.html { redirect_to "/user_dashboard", notice: "Nomination was successfully created." }
        format.json { render :show, status: :created, location: @nomination }
      else
        format.html { redirect_to reverse_map_award_to_keyword(@nomination), notice: @nomination.errors }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
        # render json: @nomination.errors
      end
    end
  end

  # PATCH/PUT /nominations/1
  # PATCH/PUT /nominations/1.json
  def update
    respond_to do |format|
      if @nomination.update(nomination_params)
        @nomination.state = "review_pending"
        @nomination.save
        format.html { redirect_to "/user_dashboard", notice: "Nomination was successfully updated." }
        format.json { render :show, status: :ok, location: @nomination }
      else
        format.html { render :edit }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominations/1
  # DELETE /nominations/1.json
  def destroy
    @nomination.destroy
    respond_to do |format|
      format.html { redirect_to "/user_dashboard", notice: "Nomination was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def pushback
    render json: params
    return
  end

  # POST /nominations/1/push_back
  def push_back
    @nomination.pushback_reason = params[:reason]
    @nomination.save!
    @nomination.push_back
    render json: { message: "Pushed back successfully" }
    return
  end

  # POST /nominations/1/forward
  def forward
    @nomination.summary = params[:summary]
    @nomination.subcommitee_member_ids = params[:members].map(&:to_i) rescue []
    @nomination.save!
    @nomination.forward
    render json: { message: "Pushed back successfully" }
    return
  end

  def l1_approval
    action_mode = params[:action_mode]
    members = params[:members].map(&:to_i)
    if action_mode == "approve"
      @nomination.l1_approval_reason = params[:comments]
      @nomination.approvers = members
      @nomination.save
      @nomination.l1_approve
      render json: { message: "Approved Successfully" }
      return
    elsif action_mode == "pushback"
      @nomination.pushback_reason = params[:comments]
      @nomination.save!
      @nomination.push_back
      render json: { message: "Approved Successfully" }
      return
    else
      @nomination.l1_rejection_reason = params[:comments]
      @nomination.rejectors = members
      @nomination.save
      @nomination.l1_reject
      render json: { message: "Rejected Successfully" }
      return
    end
  end

  def reject_single_nominee
    @nominee = @nomination.nominees.find_by(user_id: params[:user_id])
    @nominee.l1_rejection_reason = params[:reason]
    @nominee.state = "rejected"
    @nominee.save
    render json: { message: "Rejected Successfully" }
    return
  end

  def l2_approval
    action_mode = params[:action_mode]
    members = params[:members].map(&:to_i)
    if action_mode == "approve"
      @nomination.approvers = @nomination.approvers + members
      @nomination.save
      @nomination.l2_approve
      render json: { message: "Approved Successfully" }
      return
    elsif action_mode == "pushback"
      @nomination.pushback_reason = params[:comments]
      @nomination.save!
      @nomination.push_back
      render json: { message: "Approved Successfully" }
      return
    else
      @nomination.l1_rejection_reason = params[:comments]
      @nomination.rejectors = members
      @nomination.save
      @nomination.l2_reject

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/nominations/_form.html.erb
<%= form_with(model: nomination,id: 'nomination_form',local: true, :html => {:multipart => true} ) do |form| %> 
  <div class="container-fluid" id="main-form" data-action=<%= params[:action] %> data-id=<%= @nomination.id %>>
      <div class='card'>
          <div class='card-header' data-background-color='<%= @color %>'>
              <b><%= @award.title %></b>
          </div>
          <div class='card-content'>
              <div class='row'>
                  <div class='col-md-12'>
                      <div class="form-group label">
                          <!--<label class="control-label ">Select Award Type</label>-->
                          <% if params[:action] != "team_nomination" %>
                            <%# <%= form.select :award_id, options_from_collection_for_select(@awards, 'id', 'title'), {}, {class: "form-control"}%>
                            <%#= form.select :award_id, options_from_collection_for_select(@awards, 'id', 'title'), {}, {:disabled => true, class: "form-control"}%>
                            <%= form.hidden_field :award_id, :value => @award.id %>
                            <%= form.hidden_field :nomination_type, value: "individual"%>
                          <% else %>
                            <%#= form.select :award_id, options_from_collection_for_select(@awards, 'id', 'title'), {}, {:disabled => true, class: "form-control"}%>
                            <%= form.hidden_field :award_id, :value => @award.id %>
                            <%= form.hidden_field :nomination_type, value: "team"%>
                          <% end %>
                      </div>
                  </div>
                  <div class='col-md-12'>
                      <div class="form-group label">
                        <%= form.fields_for :nominees, @nomination.nominees do |s| %>
                          <label class="control-label ">Select Nominee</label>
                          <%#= s.select :user_id, options_from_collection_for_select(@users, 'id', "emp_code"), {include_hidden: false}, {:multiple => false, class: "form-control"}%>
                          <% if params[:action] == 'new' or @nomination.nomination_type == "individual" %>
                            <%= s.select :user_id, options_for_select(@users, selected: @nomination.nominees.last.user_id), {include_hidden: false}, {:multiple => false, class: "form-control"}%>
                          <% else %>
                            <%= s.select :user_id, options_for_select(@users, selected: @nomination.nominees.map(&:user_id)), {include_hidden: false}, {:multiple => true, class: "form-control"}%>
                          <% end %>
                        <% end %>
                      </div>
                  </div>
                  <div class='col-md-6'>
                      <div class="form-group label">
                          <label class="control-label ">Nominator</label>
                          <%= form.hidden_field :nominator_id, value: current_user.id %>
                          <%= form.hidden_field :nominator_type, value: current_user.class.to_s %>
                          <input type='text' class='form-control disabled' disabled value='<%= current_user.employee.name %>'>
                      </div>
                  </div>
                  <div class='col-md-6'>
                      <div class="form-group label">
                          <label class="control-label ">Date</label>
                          <%= form.hidden_field :date, value: Date.today %>
                          <input type='text' class='form-control disabled' disabled value='<%= Date.today.strftime("%d-%m-%Y")%>'>
                      </div>
                  </div>
                  
                  
                  <div class='col-md-12' id='aw1'>
                      <h5>Please answer the following</h5>
                      <table class='table table-bordered' id='rating-table'>
                          <%= form.fields_for :ratings do |rating| %>
                          <tr>
                              <td style='width: 50%'>
                                <%= rating.object.title %>
                                <%= rating.hidden_field :title, value: rating.object.title %>
                              </td>
                              <td>
                                  <div class="row">
                                      <div class='col-md-4'>
                                        Excellent (3 Pts) <%= rating.radio_button(:value, 3) %>
                                      </div>
                                      <div class='col-md-4'>
                                        Very Good (2 Pts) <%= rating.radio_button(:value, 2) %>
                                      </div>
                                      <div class='col-md-4'>
                                        Good (1 Pt) <%= rating.radio_button(:value, 1) %>
                                      </div>
                                  </div>
                              </td>
                          </tr>
                          <% end %>
                          <% unless params[:action] == "new" %>
                            <tr class='table_total_tr'>
                                <td style='width: 50%'>Total</td>
                                <td id='aw1_total'>0</td>
                            </tr>
                          <% end %>
                      </table>
                  </div>
                  
                  <div class='col-md-12'>
                    <h5>Click on success drivers demonstrated by the nominee</h5>
                    <div class='form-group'>
                    <div class="row">
                        <div class='col-md-4'>
                            <%= form.check_box :innovativeness, checked: @nomination.innovativeness %> Innovative
                        </div>
                         <div class='col-md-4'>
                            <%= form.check_box :agility %> Agility
                        </div>
                         <div class='col-md-4'>
                            <%= form.check_box :responsiveness %> Responsive
                        </div>
                         <div class='col-md-4'>
                            <%= form.check_box :performance_driven %> Performance driven
                        </div>
                         <div class='col-md-4'>
                            <%= form.check_box :ownership %> Ownership
                        </div>
                        
                    </div>
                        
                    </div>
                  </div>
                  
                  <div class="col-md-12">
                    <h5>Please answer the following</h5>
                    <table class='table table-bordered' id='rating-table'>
                          <tr>
                            <th>Assessment Params</th>
                            <th>Question</th>
                            <th>Feedback</th>
                            <th>Value Addition</th>
                            <th>Attachments</th>
                          </tr>
                          <%= form.fields_for :assessments do |assessment| %>
                          <tr>
                              <td>
                                <%= assessment.object.assessment_param%>
                                <%= assessment.hidden_field :assessment_param, value: assessment.object.assessment_param %>
                              </td>
                              <td style="width:40%;">  
                                <%= assessment.object.statement%>
                                <%= assessment.hidden_field :statement, value: assessment.object.statement %>
                              </td>
                              <td style="width:40%;">
                                <%= assessment.text_area :feedback, size: "30x10"%>
                              </td>
                              <td>
                                <%= assessment.text_field :value_addition%>
                              </td>
                              <td>
                                <%= assessment.fields_for :assessment_attachments, assessment.object.assessment_attachments do |p| %>
                                    <%= render 'nomination_attachments', p: p%>
                                    <!--
                                    <div class="field">
                                        <%#= p.label :attachment %><br>
                                        <%#= p.file_field :attachment %>
                                    </div>
                                    -->
                                <% end %>
                              </td>
                          </tr>
                         
                          <% end %>
                      </table>
                  </div>

                  <div class='col-md-12'>
                        <h5>Enter Justification</h5>
                        Please Enter Atleast 50 words.  
                        <%= form.text_area :justification %>
                    </div>
                    <div class='col-md-12'>
                        <h5>Add Attachments</h5>
                        <%= form.fields_for :nomination_attachments, @nomination.nomination_attachments do |p| %>
                            <%= render 'nomination_attachments', p: p%>
                            <!--
                            <div class="field">
                                <%#= p.label :attachment %><br>
                                <%#= p.file_field :attachment %>
                            </div>
                            -->
                        <% end %>
                        <br>
                        <br>
                        <%= link_to_add_fields 'Add More Attachments', form, :nomination_attachments%>
                    </div>
                    <div class='card-footer'>

                        <%= form.submit "Add Nomination", class: 'btn btn-success pull-right' %>
                    </div>
              </div>
          </div>
      </div>
  </div>
<% end %>
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<script>
    $(document).ready(function () {
        CKEDITOR.replace('nomination[justification]');
        $('select').select2();

        //Filling up ratings once
        var awardId = $('#nomination_award_id').val();
        $('.hidden').show();
        if($('#main-form').data('action') !== 'edit') {
            $.get('/nominations/load_rating_form/' + awardId + '/' + $('#main-form').data('id'), function(data, status){
                $('#rating-table').html(data);
                calculate_total();
            });
        }

        // CKEDITOR.instances.nomination_justification.on("blur",function(e){
        //     var data = CKEDITOR.instances.nomination_justification.getData();
        //     if(data.split(' ').length < 50){
        //         alert("More Detailing Required");
        //         CKEDITOR.instances.nomination_justification.focus();
        //     }

        // });

       $("[data-form-prepend]").click(function(e) {
            var obj = $($(this).attr("data-form-prepend"));
            obj.find("input, select, textarea").each(function() {
                $(this).attr("name", function() {
                return $(this)
                    .attr("name")
                    .replace("new_record", $('input:file').length);
                });
            });
            obj.insertBefore(this);
            return false;
        });
    });

    $('#nomination_award_id').on('change', function() {
        var awardId = $(this).find(":selected").val();
        $('.hidden').show();
        $.get('/nominations/load_rating_form/' + awardId + '/' + $('#main-form').data('id'), function(data, status){
            $('#rating-table').html(data);
            calculate_total();
        });
    });
    $('#nomination_nominees_attributes_0_user_id').on('change', function(){
        <% if params[:action] == 'team_nomination' %>
            if ($('#nomination_nominees_attributes_0_user_id').select2('data').length < 2) {
                // alert("Need at least one group");
                // event.preventDefault();
                $.notify("Need minimum two nominess","warning");
            }
        <% end %>
    })

    function calculate_total(){
        $('input[type=radio]').on("change", function() { 
            var total = 0;
            $('input[type="radio"]:checked').each(function() {
                total = total + parseInt($(this).val())
            }); 
            console.log(total)
            $("#aw1_total").html(total);
        });
    }
   
</script>

app/views/nominations/_nomination_attachments.erb
<div class="field">
    <%#= p.label :attachment %><br>
    <% if p.object.attachment.identifier.nil? %>
        <%= p.file_field :attachment, data: { placeholder: p.object.attachment || "No file selected" } %>
    <% else %>
        <%#= p.file_field :attachment, data: { placeholder: p.object.attachment || "No file selected" } %>
        <a href="<%= p.object.attachment.url %>"><%= p.object.attachment.identifier %></a>
        <%= p.check_box :_destroy%>
        <%= p.label :delete%>
    <% end %>
    
</div>

app/views/nominations/_rating_form.html.erb
<tboby>
    <% @rating_scales.each_with_index do |r, index| %>
        <tr>
            <td style="width: 50%">
            <%= r.title %>
            <input value="<%= r.title %>" type="hidden" name=<%= "nomination[ratings_attributes][#{index}][title]" %> id= <%= "nomination_ratings_attributes_#{index}_title" %>
            </td>
            <td>
                <div class="row">
                    <div class="col-md-4">
                    Excellent (3 Pts) <input type="radio" value="3" name=<%= "nomination[ratings_attributes][#{index}][value]" %> id=<%= "nomination_ratings_attributes_#{index}_value_3"%>>
                    </div>
                    <div class="col-md-4">
                    Very Good (2 Pts) <input type="radio" value="2" name=<%= "nomination[ratings_attributes][#{index}][value]" %> id=<%= "nomination_ratings_attributes_#{index}_value_2"%>>
                    </div>
                    <div class="col-md-4">
                     Good (1 Pt) <input type="radio" value="1" name=<%= "nomination[ratings_attributes][#{index}][value]" %> id=<%= "nomination_ratings_attributes_#{index}_value_1"%>>
                    </div>
                </div>  
            </td>
        </tr>
    <% end %>
    <tr class='table_total_tr'>
        <td style='width: 50%'>Total</td>
        <td id='aw1_total'>0</td>
    </tr>
</tbody>

app/views/nominations/edit.html.erb
<h4>Editing Nomination</h4>

<%= render 'form', nomination: @nomination %>

<%= link_to 'Show', @nomination %> |
<%= link_to 'Back', nominations_path %>

app/views/nominations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nominations</h1>

<table>
  <thead>
    <tr>
      <th>Award</th>
      <th>Nomination type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nominations.each do |nomination| %>
      <tr>
        <td><%= nomination.award_id %></td>
        <td><%= nomination.nomination_type %></td>
        <td><%= link_to 'Show', nomination %></td>
        <td><%= link_to 'Edit', edit_nomination_path(nomination) %></td>
        <td><%= link_to 'Destroy', nomination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nomination', new_nomination_path %>

app/views/nominations/individual_nominations.html.erb
<%= render 'form', nomination: @nomination %>

<%#= link_to 'Back', nominations_path %>

app/views/nominations/new.html.erb
<%= render 'form', nomination: @nomination %>

<%= link_to 'Back', nominations_path %>

app/views/nominations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Award:</strong>
  <%= @nomination.award_id %>
</p>

<p>
  <strong>Nomination type:</strong>
  <%= @nomination.nomination_type %>
</p>

<%= link_to 'Edit', edit_nomination_path(@nomination) %> |
<%= link_to 'Back', nominations_path %>

app/views/nominations/team_nomination.html.erb
<%= render 'form', nomination: @nomination %>

<%#= link_to 'Back', nominations_path %>